### ISSUE TITLE
Extract script doesn't run

### ISSUE THREAD

**Issue by ecrona** [APSL/redux-i18n#10]
Hey

I tried the extract-script, but it doesn't run because of what seems to be an ES6-based error, it 

var srcPath = `${args.source || 'src'}/**/*.js*`;
...........................^
SyntaxError: Unexpected token ILLEGAL

(There are template strings there that can't be rendered on this comment section apparently)

Do I need to install babel or something alike to make it work? Thanks

**Comment by francescarpi** [comment]
Hi!

Maybe, I'm not sure but can you add **es2015** in your **.babelrc**'s presets, please?

You must install **babel-preset-es2015** package.

Please, tell me if it resolved.

Thanks.

**Comment by ecrona** [comment]
I'm gonna try when I get home, thanks! I'll post the results

**Comment by ecrona** [comment]
It seems I get the same problem, I wonder if I need to install babel or some other dependency for these scripts to run? Because I only installed "redux-i18n --save", and now "babel-preset-es2015 --save-dev" and included the file .babelrc in the root of my project with the contents "{ "presets": ["es2015"] }".

Is there anything else I missed? Thanks

**Comment by ecrona** [comment]
Okay I managed to get it to work.

Apparently, my node was at a very low version, so I simply updated it to 7.2.0 and everything ran smoothly, without the need of  installing babel or presets.

However, I have another suggestion, but I'll make a separate issue.

Thanks!

**Comment by francescarpi** [comment]
Hi!

Glad to know that it work for you. Tomorrow I going to add a FAQ file with this common problems.

Thanks.
