### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by ecrona** [APSL/redux-i18n#11]
Hello again.

Sorry to bother you guys, but I'm very fond of this package, it suits my needs very well.

I have a suggestion, to support Typescript. Currently, the exporting function only goes through js* files, going through ts* files would be greatly appreciated, possibly to customize this pattern through script parameters. It would also be really cool to be able to configure the name of the translations file when importing, as it's now named translations.js, where as translations.ts would work better for me.

Perhaps to include a definitions file as well, this would require quite some work, and I'd do it myself if I had the time, but it would be great to have, since Typescript is growing, as it's a remarkable addition to JavaScript for closer type control, and so on.

Simply something to think about, It'd be super if some day, you'd find the time and energy to add support for the ts-files at least, that'd be glorious.

Thanks!

**Comment by francescarpi** [comment]
Hi!

I'm going to think about that and hope I give you good news soon.

Best regards.

**Comment by renchap** [comment]
This has been done in #57
