### ISSUE TITLE
Pass JSX as params

### ISSUE THREAD

**Issue by tsi** [APSL/redux-i18n#12]
Is there any way to pass JSX as parameter to the translation function? 
I'm trying to do something like this:
```js
      const name = <span className="name">{user.name}</span>;
      return this.context.t("Hello {name}!", {name: name})
```

Thanks!

**Comment by francescarpi** [comment]
Hi!

Wow, it's a great question! 

It isn't possible, now, but I going to work with this improvement.

Thanks.

**Comment by shizpi** [comment]
Any idea when JSX will be supported?

**Comment by francescarpi** [comment]
Hi!
I've good news for you. Please, download latest version (1.1.5) and take a look to documentation:

https://github.com/APSL/redux-i18n#html-object-as-parameter

Best regards.

**Comment by shizpi** [comment]
Awesome! Thanks

**Comment by pablen** [comment]
Thanks for this!
But after trying it myself I noticed the HTML passed as a parameter is scaped so the actual HTML code is rendered. Is there any way to avoid that behaviour?

**Comment by francescarpi** [comment]
Hi,
ok, I'm going to check.
Thanks

**Comment by francescarpi** [comment]
Hi,

I just see that we can't print html directly for security reasons. You should use "dangerouslySetInnerHTML" method. I've updated documentation in this branch:

https://github.com/APSL/redux-i18n/tree/trans_to_reducer#html-object-as-parameter

I'll merge to master as soon as possible.
Thanks.

**Comment by pablen** [comment]
Cool.
Really grateful for this tool. I was worried when I had to add i18n to my project but this little tool solved the problem with minimal effort.
Thanks!
