### ISSUE TITLE
ie11 Dollar sign bug

### ISSUE THREAD

**Issue by gannoncurran** [APSL/redux-i18n#13]
Hi —

We've happily been using redux-i18n, but recently discovered a bug that affects our app (mostly in Internet Explorer 11).

Javascript's [String.prototype.replace()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace) interprets '$'s in params as replacement patterns unless they're escaped. Worse, IE interprets '$0' as a '$n' pattern and inserts the nth parenthesized submatch.

For example:
`t("You’ll be charged an additional {amount} per hour", {amount: '$0.75'})`
renders in ie11 as:
`You’ll be charged an additional {amount}.75 per hour`

Additionally, all browsers will render things like
`t("I love dollar signs {dollarSigns}!", {dollarSigns: '$$'})`
as:
`I love dollar signs $!` instead of the expected `I love dollar signs $$!`

I offer PR https://github.com/APSL/redux-i18n/pull/14 as a fix.

Thanks!

**Comment by francescarpi** [comment]
Thanks!

Good job.

**Comment by gannoncurran** [comment]
Hey thanks for rolling in! This helps us out a lot.
Happy to contribute, and really appreciate this library.
