### ISSUE TITLE
Tick's support

### ISSUE THREAD

**Issue by stuk88** [APSL/redux-i18n#20]
Hey
I have added a tick to a word, and the extract just cuts the text where the tick is.
The problem is with the regex.

For example, the sentence:
`Tom's house is very big`
The text line in the translation will be:
`Tom`

**Comment by francescarpi** [comment]
Hi,

take a look https://github.com/APSL/redux-i18n/pull/23

I've a little problem because tests pass on Travis, but not in my local. I'm looking for that.

Thanks

**Comment by francescarpi** [comment]
Hi,

I was confused. Tests not pass on Travis. Please, make sure that tests pass in your local before send PR.

https://travis-ci.org/APSL/redux-i18n/jobs/219370888

Thanks

**Comment by francescarpi** [comment]
I just created this branch for work with that.

https://github.com/APSL/redux-i18n/tree/fixsinglequotes

**Comment by francescarpi** [comment]
Hi,

I've published a new version (1.2.2) that fix this bug.

Best regards.
