### ISSUE TITLE
Use a default language different from 'en'

### ISSUE THREAD

**Issue by brunoreis** [APSL/redux-i18n#24]
My first language is 'pt-br', but the system seems to be done in such a way that en is always the reference. Is there a way to set 'pt-br' as default and have a translation table to 'en'?

**Comment by francescarpi** [comment]
Hi!

Yes. You can call *setLanguage* action before your app is mounted, but don't worry, because I just created a new version (1.3.0) where you can set the *initiallang* when component is declared.

Please, take a look at *usage* section (https://github.com/APSL/redux-i18n#usage)

Best regards.

**Comment by brunoreis** [comment]
Just to keep here as a reference to other looking for it. I was able to set initiallang to have pt-br as the base reference: 

```jsx
<I18n translations={translations} initialLang="pt-br">
```
 define the translations using pt-br as the keys: 

```js
export const translations = {
  "en": {
    "Mensagens": "Messages",
    "Conversas": "Threads",
  }
}
```

And call "t" inside my component using pt-br: 

```jsx
const MessageStatus = (
	{...},
	{t}
) => {
	
	let text = t("Mensagens")
```
