### ISSUE TITLE
Option for custom regexp when extracting

### ISSUE THREAD

**Issue by renchap** [APSL/redux-i18n#26]
I am using CoffeeScript for some of my React components, and currently `i18n_extract` only reads `.js` / `.jsx` files.
It would be great to have an additional argument to either specify the extensions of the source files, or the full regexp.

Changing `srcPath` to 
```js
var srcPath = `${args.source || 'src'}/**/*.{js,coffee}*`;
```

works fine for me. I expect it will also be helpful for Typescript user, as Typescript is a superset of JS.

**Comment by francescarpi** [comment]
Hi, 
ok. I'll try to do as soon as possible.

Thanks.

**Comment by francescarpi** [comment]
Hi Renaud!

It's done!

https://www.npmjs.com/package/redux-i18n#extract-texts-and-build-templatepot

Get last 1.3.2 version.

Best regards.

**Comment by renchap** [comment]
Thanks a lot!
