### ISSUE TITLE
Support for defaultLocale

### ISSUE THREAD

**Issue by mihaerzen** [APSL/redux-i18n#28]
Is there a way to set `defaultLocale` which would basically default to a certain language if translation is not found?

For eg. we have all translations for `en` but missing some for `de`. In this case we would set `defaultLocale` to `en` and make sure that user with locale `de` does not see empty text but rather `en` translations.

Thank you for the response.

p.s.: As seen in [https://www.npmjs.com/package/i18n](https://www.npmjs.com/package/i18n)

**Comment by francescarpi** [comment]
Hi Miha,
currently, if you have the next translation:

`context.t('Hello world')`

...and not exist in _DE_, the default output is in English version. But I understand that if you have this:

`context.t('__hello_world__')`

You would like that default translated output to be "Hello world" and not "__hello_word__".

Ok, I'm going to work for add "defaultLocale" configuration's parameter.

Best regards.

**Comment by mihaerzen** [comment]
But what if I want it the other way around? Scenario would be:

Given app has 100% of German translations and 80% of English translations
And user has language set to English
And defaultLocale for i18n is set to German
When user openes the app
Then user will see 80% of English text
And 20% of German text

Meaning option to change defaultLocale. I can provide example to explain better if necessary.

**Comment by mihaerzen** [comment]
Also what you wrote is correct yes.

**Comment by francescarpi** [comment]
Hi Miha,
sorry for not say anything before. I've have a lot of work and I'll try to do as soon as possible.

To be patient :)

**Comment by mihaerzen** [comment]
Hey no worries. Plese write if you need help, I'm happy to contribute.

**Comment by francescarpi** [comment]
Hi,
done in master branch. I'll build a new tag in next days.
Best regards.

**Comment by francescarpi** [comment]
Hi,
I've created a new tag ;)
