### ISSUE TITLE
initialLang attribute is forcing language change back to initialLang

### ISSUE THREAD

**Issue by pablocoberly** [APSL/redux-i18n#30]
If I dispatch an action to change the language to something other than `initialLang`, the component always dispatches an action to set the language to back to `initialLang`. 

I believe the component should only use `initialLang` if `lang` has not already been set. For example, I set the lang for my application in redux state before the first render of the component, the i18n component will reads this as the lang, but then dispatches an action to reset it to `initialLang`.

It seems `initialLang` isn't being read from state, and I can't set it from server-side configuration file using a library like `config`.

As an aside, the default prop value for `initialLang` is `en`, which I don't use (I use `en-GB`). A default `initialLang` which seems counter-intuitive.

For the time-being I'm going to change my dependency to the previous version, but if you have thoughts on how I can resolve this, I'd appreciate it.

**Comment by francescarpi** [comment]
Hi Pablo,

You're right. I'll fix this bug today.

Best regards.

**Comment by francescarpi** [comment]
Hi,

I was thinking about that, and is not possible that you set initialLang when you define your component?

For example:

```javascript
      <Provider store={this.store}>
        <I18n translations={translations} initialLang="en-GB">
          ...
        </I18n>
      </Provider>
```

**Comment by pablocoberly** [comment]
Sorry just saw your response. Will check and get back to you.

**Comment by pablocoberly** [comment]
It's actually much better now because I don't have to dispatch an action to change the language at all, I can just reset the initialLang prop on the component. Thanks again.

**Comment by sorokinvj** [comment]
Hey guys, I stuck with the problem, that redux-i18n sometimes change the language to initialLang (and somtimes not) just after the initilization of component. I init setLanguage as action like this:

```
import { setLanguage } from "redux-i18n"

export const switchLanguage = (language) => (dispatch) => {
    dispatch(setLanguage(language));
}
```
and then just dispatch that action whenever the language switcher is clicked. 

So, the question is how I can control the initilization of Redux i18n and an action that dispatched with that init? Could I override this(init) behaviour? Why some components trigger this init and some not?
