### ISSUE TITLE
HOC error

### ISSUE THREAD

**Issue by shizpi** [APSL/redux-i18n#44]
Hello,

I want to use your HOC to use the function as "translate", but I have this error:
![screenshot from 2017-08-16 19-24-01](https://user-images.githubusercontent.com/10537219/29376344-89aa136c-82b8-11e7-9907-d24d9d5d1a9f.png)

I tried without redux connect but I always get the same issue.
I'm using react-router 4

**Comment by gautamvij** [comment]
Facing same issue.

**Comment by fhessenberger** [comment]
There is an error with the documentation. The HOC is not exported as default, but as `localize`.
`import { localize } from 'redux-i18n'`

Submitted pull request #48

**Comment by shizpi** [comment]
Oh, it works like that, thanks!
