### ISSUE TITLE
Extract method broken

### ISSUE THREAD

**Issue by jonathancalb** [APSL/redux-i18n#6]
When I run the "extract" method gives me the following error:

> ../node_modules/redux-i18n/bin/extract_utils.js:30
>   let group = {}
>   ^^^
> SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

Im runing node v4.0.0

**Comment by francescarpi** [comment]
Hi!

What npm version do you have?

**Comment by francescarpi** [comment]
Hi,

Did you solved the problem?

I think that is for your project configuration. Not for a _redux-i18n_ bug.

Thx
