### ISSUE TITLE
Context.t not being passed on server-side (isomorphic) render

### ISSUE THREAD

**Issue by shankie-san** [APSL/redux-i18n#66]
The docs allude to the fact that there might be an additional configuration step to make isomorphic work, but I can't for the life of me work out what it is.

Say I've got i18n set up like this:

```js
    <Provider store={store}>
      <I18n translations={translations} initialLang="en-GB" fallbackLang="en-GB">
        <Router history={history}>{routes}</Router>
      </I18n>
    </Provider>
```

and a component like:

```js
const ComponentName = (props, {t}) => {
  return (
    <div>
      {t("Traduisez-moi!")}
    </div>
  );
};

ComponentName.contextTypes = {
  t: React.PropTypes.func.isRequired,
};
```

it all works fine if I don't render on the server, but as soon as I introduce isomporhic, the server falls over on first page load with errors (on the server side) like:

```bash
Warning: Failed context type: The context `t` is marked as required in `ComponentName`, but its value is `undefined`.
    in ComponentName (created by Connect(ComponentName))
    in Connect(ComponentName)
    in div
    in MuiThemeProvider (created by MuiThemeProviderWrapper)
    in MuiThemeProviderWrapper
    in App (created by Connect(App))
    in Connect(App) (created by withTheme(Connect(App)))
    in withTheme(Connect(App)) (created by RouterContext)
    in RouterContext
    in JssProvider
    in Provider
TypeError: t is not a function
    at ComponentName (/usr/src/app/client/App/ComponentName.js:67:36)
    at /usr/src/node_modules/react-dom/lib/ReactCompositeComponent.js:303:16
    at measureLifeCyclePerf (/usr/src/node_modules/react-dom/lib/ReactCompositeComponent.js:73:12)
    ...
```

Obviously I can hack it and only use tranlsations on the client, but it doesn't feel right...

EDIT:

That's not true because, although I can remove my `<I18n />` component on the client site, all of my components are now tightly bound to having the `t` context around...

**Comment by shankie-san** [comment]
Ah, of course, it's always (not always, but a lot of the time!) the case that as soon as you post an issue, you work out a solution.

In the example above, the `<I18n>` wrapper was quite high in the stack, just below my `<Provider>`. But, in between that and the content that actually needs translating, I have React Router v3 routes and a Material UI `<MuiThemeProvider/>`.  At any rate, moving it down my tree seems to have solved it.

I'd happily like to hear though if anyone has any theories on why this might not pass context through other wrapper components on the server side!

Closing for now...

**Comment by mrchief** [comment]
I'm using React Router 4 and it needs to be higher than the router. Otherwise I get `t` as undefined. :)

**Comment by shankie-san** [comment]
I've also found that, in some situations where `context.t` isn't working, the HOC approach works fine
