### ISSUE TITLE
Stateless components

### ISSUE THREAD

**Issue by mac2000** [APSL/redux-i18n#7]
Can not find docs, tests, samples for stateless components is it possible to use redux-i18n with them at all?

E.g. dummy components do not have this, context, etc

```js
import React from 'react'

const Foo = () => <h1>{context.t("Hello World")}</h1>

Foo.contextTypes = {
	t: React.PropTypes.func.isRequired
}

export default Foo
```

May be some kind of connect may pass translation function via props or something like this?

**Comment by francescarpi** [comment]
Hi,

You can access to context inside your stateless function.

For example:
```javascript
const Foo = ({}, context) => <h1>{context.t("Hello World")}</h1>
```

I will update documentation to add this example, soon.

Thx

**Comment by mac2000** [comment]
Got it, thank you for so fast response, in case if you want - I have already send you PR so this note will not loose

**Comment by mrchief** [comment]
@mac2000 The docs should also mention that this line is important for SFCs

```
Foo.contextTypes = {
    t: React.PropTypes.func.isRequired
}
```
