### ISSUE TITLE
React 16 language switching does not work

### ISSUE THREAD

**Issue by yarron** [APSL/redux-i18n#73]
After updating to React 16.2.0 and after switching the language(REDUX_I18N_SET_LANGUAGE) , an error occurs that occurs in the dependent library "react-deep-force-update". The error appears only in the compiled version and does not appear in the local version.

`main.6296193c.js:2182 TypeError: Cannot read property '_pendingForceUpdate' of undefined
    at setPendingForceUpdate (main.6296193c.js:22530)
    at traverseRenderedChildren (main.6296193c.js:22516)
    at deepForceUpdate (main.6296193c.js:22550)
    at I18n.componentDidUpdate (main.6296193c.js:28831)
    at commitLifeCycles (main.6296193c.js:2164)
    at c (main.6296193c.js:2175)
    at k (main.6296193c.js:2178)
    at p (main.6296193c.js:2179)
    at batchedUpdates (main.6296193c.js:2185)
    at qb (main.6296193c.js:2036)
x @ main.6296193c.js:2182
c @ main.6296193c.js:2176
k @ main.6296193c.js:2178
p @ main.6296193c.js:2179
batchedUpdates @ main.6296193c.js:2185
qb @ main.6296193c.js:2036
ob @ main.6296193c.js:2036
batchedUpdates @ main.6296193c.js:2037
dispatchEvent @ main.6296193c.js:2040
main.6296193c.js:22530 Uncaught TypeError: Cannot read property '_pendingForceUpdate' of undefined
    at setPendingForceUpdate (main.6296193c.js:22530)
    at traverseRenderedChildren (main.6296193c.js:22516)
    at deepForceUpdate (main.6296193c.js:22550)
    at I18n.componentDidUpdate (main.6296193c.js:28831)
    at commitLifeCycles (main.6296193c.js:2164)
    at c (main.6296193c.js:2175)
    at k (main.6296193c.js:2178)
    at p (main.6296193c.js:2179)
    at batchedUpdates (main.6296193c.js:2185)
    at qb (main.6296193c.js:2036)
setPendingForceUpdate @ main.6296193c.js:22530
traverseRenderedChildren @ main.6296193c.js:22516
deepForceUpdate @ main.6296193c.js:22550
componentDidUpdate @ main.6296193c.js:28831
commitLifeCycles @ main.6296193c.js:2164
c @ main.6296193c.js:2175
k @ main.6296193c.js:2178
p @ main.6296193c.js:2179
batchedUpdates @ main.6296193c.js:2185
qb @ main.6296193c.js:2036
ob @ main.6296193c.js:2036
batchedUpdates @ main.6296193c.js:2037
dispatchEvent @ main.6296193c.js:2040
`
![orca - inbox 2017-12-25 15-19-39](https://user-images.githubusercontent.com/10478293/34340311-d03fa3d2-e992-11e7-9ec8-e381ed819279.jpg)
![orca - inbox 2017-12-25 15-29-16](https://user-images.githubusercontent.com/10478293/34340312-d05cbb66-e992-11e7-96b9-85ea63d046a1.jpg)

**You need to update the library react-deep-force-update to version 2.1.1**

**Comment by clovnrian** [comment]
Hi, I have also problem with re-render components connected on redux. I updated to React 16.2 and redux-i18n to 1.5.12.
I don't see any errors on localhost or production. I try update react-deep-force-update library to version 2.1.1. but it still not working.
Downgrade React to version 15.6.2 don't help. 

Redux-i18n in version 1.5.4 is working well with React 16.2, but I can't use it, because I need to use getTranslateFunction import.

Version 1.5.5 also not working.

**Comment by shankie-san** [comment]
I'd like to add that I'm having a similar issue since upgrading to React 16. In my case, I'm having inconsistent rendering of translations when navigating between `connect()`ed components. I'll try downgrading to 1.5.4 and report back

**Comment by martuanez** [comment]
Any updates on this? I'm not being able to have the setLanguage working either, and the state has an empty object for translations may be that's part of the reason why it isn't working

**Comment by shankie-san** [comment]
If it's any help, I've narrowed this down. Language switching _does_ work in React 16, but only in components that aren't wrapped in `connect()` from `react-redux`. Which, annoyingly, is surely almost all of anyone's application. I noticed that my menu was being translated correctly, because it's not `connect`ed to Redux.

**Comment by francescarpi** [comment]
Sorry people, 
can you upgrade the react-deep-force-update to version 2.1.3 and confirm me if it goes ok, please?

**Comment by francescarpi** [comment]
Hi mates,
fixed in version 1.5.16.
